spring:
  application:
    name: @project.artifactId@
  config:
    import: file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    
  data:
    redis:
      port: ${REDIS_PORT}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
          

anitrace:
  security:
    token:
      jwt:
        audience: ${JWT_AUDIENCE:anitrace}
        access-token:
          lifespan: ${ACCESS_TOKEN_LIFESPAN:15m}
        refresh-token:
          enabled: ${REFRESH_TOKEN_ENABLED:true}
          lifespan: ${REFRESH_TOKEN_LIFESPAN:1d}
        revocation:
          enabled: ${TOKEN_REVOCATION_ENABLED:true}
        public-key:
          path: ${PUBLIC_KEY_PATH:file:.keys/public.pem}
        private-key:
          path: ${PRIVATE_KEY_PATH:file:.keys/private.pem}
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
      allowed-methods: ${CORS_ALLOWED_METHODS:*}
  version: @project.version@