spring:
  application:
    name: @project.artifactId@
  config:
    import: file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    
  data:
    redis:
      port: ${REDIS_PORT}

anitrace:
  security:
    token:
      jwt:
        audience: ${JWT_AUDIENCE:anitrace}
        access-token:
          lifespan: ${ACCESS_TOKEN_LIFESPAN:15m}
        refresh-token:
          lifespan: ${REFRESH_TOKEN_LIFESPAN:1d}
        public-key-file: ${PUBLIC_KEY_FILE:file:.keys/public.pem}
        private-key-file: ${PRIVATE_KEY_FILE:file:.keys/private.pem}